# Generated by Django 5.1.15 on 2026-08-21 04:12

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='DanmakuVideo',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('bvid', models.CharField(max_length=32, unique=True, verbose_name='BV号')),
                ('cid', models.BigIntegerField(default=0, verbose_name='视频cid')),
                ('title', models.CharField(max_length=500, verbose_name='标题')),
                ('up_mid', models.BigIntegerField(default=0, verbose_name='UP主ID')),
                ('up_name', models.CharField(blank=True, max_length=100, verbose_name='UP主')),
                ('tname', models.CharField(blank=True, max_length=100, verbose_name='分区')),
                ('duration', models.IntegerField(default=0, verbose_name='时长(秒)')),
                ('danmaku_count', models.IntegerField(default=0, verbose_name='弹幕数')),
                ('source', models.CharField(default='manual', max_length=20, verbose_name='来源')),
                ('fetch_status', models.CharField(default='pending', max_length=20, verbose_name='抓取状态')),
                ('fetched_at', models.DateTimeField(blank=True, null=True, verbose_name='抓取时间')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='创建时间')),
            ],
            options={
                'verbose_name': '弹幕视频',
                'verbose_name_plural': '弹幕视频',
                'db_table': 'danmaku_video',
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='DanmakuAnalysis',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('bvid', models.CharField(db_index=True, max_length=32, verbose_name='BV号')),
                ('snapshot', models.JSONField(blank=True, default=dict, verbose_name='分析结果')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='生成时间')),
                ('video', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='analyses', to='analytics.danmakuvideo', verbose_name='视频')),
            ],
            options={
                'verbose_name': '弹幕分析',
                'verbose_name_plural': '弹幕分析',
                'db_table': 'danmaku_analysis',
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='DanmakuRecord',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('bvid', models.CharField(db_index=True, max_length=32, verbose_name='BV号')),
                ('cid', models.BigIntegerField(default=0, verbose_name='视频cid')),
                ('dmid', models.BigIntegerField(default=0, verbose_name='弹幕ID')),
                ('progress_ms', models.BigIntegerField(default=0, verbose_name='弹幕位置(毫秒)')),
                ('mode', models.IntegerField(default=1, verbose_name='模式')),
                ('fontsize', models.IntegerField(default=25, verbose_name='字号')),
                ('color', models.BigIntegerField(default=0, verbose_name='颜色')),
                ('mid_hash', models.CharField(blank=True, max_length=32, verbose_name='用户哈希')),
                ('content', models.TextField(verbose_name='弹幕内容')),
                ('ctime', models.BigIntegerField(db_index=True, default=0, verbose_name='发送时间戳')),
                ('weight', models.IntegerField(default=0, verbose_name='权重')),
                ('pool', models.IntegerField(default=0, verbose_name='弹幕池')),
                ('attr', models.BigIntegerField(default=0, verbose_name='属性')),
                ('source', models.CharField(default='manual', max_length=20, verbose_name='来源')),
                ('fetched_at', models.DateTimeField(auto_now_add=True, verbose_name='抓取时间')),
                ('video', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='danmakus', to='analytics.danmakuvideo', verbose_name='视频')),
            ],
            options={
                'verbose_name': '弹幕记录',
                'verbose_name_plural': '弹幕记录',
                'db_table': 'danmaku_record',
                'ordering': ['progress_ms'],
                'indexes': [models.Index(fields=['bvid', 'progress_ms'], name='danmaku_rec_bvid_74254d_idx')],
                'unique_together': {('bvid', 'dmid')},
            },
        ),
    ]
